# Generated by Django 2.2.5 on 2020-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yunicon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
