# Generated by Django 2.2.5 on 2020-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200731_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='image',
            field=models.ImageField(default='uploads/article/202007/a.png', upload_to='uploads/article/%Y%m', verbose_name='文章图片'),
        ),
    ]
