# Generated by Django 2.2.5 on 2020-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200731_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='image',
            field=models.ImageField(default='uploads/article/202007/p01.jpg', upload_to='uploads/article/%Y%m', verbose_name='文章图片'),
        ),
    ]
