# Generated by Django 2.2.5 on 2020-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='内容')),
                ('date', models.DateField(auto_now=True)),
                ('icon', models.CharField(max_length=160, verbose_name='头像')),
            ],
            options={
                'verbose_name': '留言表',
                'db_table': 'message',
            },
        ),
    ]
